---
# file tasks/vagrant-box/main.yml
# Vagrant defaults for boxing the image.

  - name: Add vagrant user
    user:
      name: vagrant
      state: present
      password: vagrant

  - name: Add to sudoers
    lineinfile: 
      path: /etc/sudoers
      state: present
      regexp: '^vagrant'
      line: 'vagrant        ALL=(ALL)       NOPASSWD: ALL'


  - name: Configure Vagrant .ssh directory.
    file:
      path: /home/vagrant/.ssh
      state: directory
      owner: vagrant
      group: vagrant
      mode: 0700

  - name: Get Vagrant's public key.
    get_url:
      url: https://github.com/mitchellh/vagrant/raw/master/keys/vagrant.pub
      dest: /home/vagrant/.ssh/authorized_keys
      owner: vagrant
      group: vagrant
      mode: 0600